//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TranslatorLibrary.lang {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslatorLibrary.lang.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 本地人工翻译(见说明) 的本地化字符串。
        /// </summary>
        internal static string ArtificialTranslator {
            get {
                return ResourceManager.GetString("ArtificialTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Azure 的本地化字符串。
        /// </summary>
        internal static string AzureTranslator {
            get {
                return ResourceManager.GetString("AzureTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 百度翻译 的本地化字符串。
        /// </summary>
        internal static string BaiduTranslator {
            get {
                return ResourceManager.GetString("BaiduTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 彩云小译 的本地化字符串。
        /// </summary>
        internal static string CaiyunTranslator {
            get {
                return ResourceManager.GetString("CaiyunTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ChatGPT 的本地化字符串。
        /// </summary>
        internal static string ChatGPTTranslator {
            get {
                return ResourceManager.GetString("ChatGPTTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 DeepL 的本地化字符串。
        /// </summary>
        internal static string DeepLTranslator {
            get {
                return ResourceManager.GetString("DeepLTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 译典通 的本地化字符串。
        /// </summary>
        internal static string DreyeTranslator {
            get {
                return ResourceManager.GetString("DreyeTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 谷歌翻译(公共接口) 的本地化字符串。
        /// </summary>
        internal static string GoogleCNTranslator {
            get {
                return ResourceManager.GetString("GoogleCNTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 IBM翻译 的本地化字符串。
        /// </summary>
        internal static string IBMTranslator {
            get {
                return ResourceManager.GetString("IBMTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 JBeijing 的本地化字符串。
        /// </summary>
        internal static string JBeijingTranslator {
            get {
                return ResourceManager.GetString("JBeijingTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 金山快译 的本地化字符串。
        /// </summary>
        internal static string KingsoftFastAITTranslator {
            get {
                return ResourceManager.GetString("KingsoftFastAITTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无翻译 的本地化字符串。
        /// </summary>
        internal static string NoTranslator {
            get {
                return ResourceManager.GetString("NoTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腾讯云翻译 的本地化字符串。
        /// </summary>
        internal static string TencentOldTranslator {
            get {
                return ResourceManager.GetString("TencentOldTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 火山翻译 的本地化字符串。
        /// </summary>
        internal static string VolcanoTranslator {
            get {
                return ResourceManager.GetString("VolcanoTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 小牛翻译 的本地化字符串。
        /// </summary>
        internal static string XiaoniuTranslator {
            get {
                return ResourceManager.GetString("XiaoniuTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yandex翻译 的本地化字符串。
        /// </summary>
        internal static string YandexTranslator {
            get {
                return ResourceManager.GetString("YandexTranslator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有道智云 的本地化字符串。
        /// </summary>
        internal static string YoudaoZhiyun {
            get {
                return ResourceManager.GetString("YoudaoZhiyun", resourceCulture);
            }
        }
    }
}
