<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>


  <ItemGroup>
    <ProjectReference Include="..\Mikoto\Mikoto.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Update="Serilog" Version="4.4.0" />
  </ItemGroup>

</Project>
